name: "🏷️ Add label by PR file"

permissions:
  pull-requests: write

on:
  pull_request_target:
    types: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          configuration-path: ".github/workflows/config/add-label-by-pr-file-config.yml"
          repo-token: "${{ secrets.KIRARI_TOKEN }}"
          sync-labels: true
