name: "🏷️ Add wip label when draft"

permissions:
  pull-requests: write

on:
  pull_request_target:
    types: [opened, converted_to_draft]

jobs:
  add_wip_label:
    if: github.event.pull_request.draft == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.KIRARI_TOKEN }}
          labels: [Status] Needs review👀
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.KIRARI_TOKEN }}
          labels: [Status] WIP🚧