name: "🏷️ Add review label when ready"

permissions:
  pull-requests: write

on:
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  add_review_label:
    if: github.event.pull_request.draft != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.KIRARI_TOKEN }}
          labels: [Status] WIP🚧
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.KIRARI_TOKEN }}
          labels: [Status] Needs review👀