name: "🏷️ Add label by PR name"

permissions:
  pull-requests: write

on:
  pull_request_target:
    types: [opened]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3.1.0
        with:
          configuration-path: ".github/workflows/config/add-label-by-pr-name-config.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.KIRARI_TOKEN }}