name: "🔖 Assign repo members to new issue"
on:
  issues:
    types: [opened]
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: pozil/auto-assign-issue@v1
        if: github.actor != 'dependabot[bot]'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ secrets.REPO_ASSIGNEE }}