name: "✒ Lint text files with textlint using reviewdog"

on:
  pull_request_target:
    types:
      - opened
      - synchronize
    branches:
      - develop
    paths:
      - 'docs/*.md'

jobs:
  reviewdog-github-check:
    name: "✒ lint text"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: textlint-github-pr-review
        uses: tsuyoshicho/action-textlint@v3
        with:
          github_token: ${{ secrets.KIRARI_TOKEN }}
          reporter: github-pr-review
          textlint_flags: "docs/**"