name: "✑ Lint action with actionlint using reviewdog"

on:
  pull_request_target:
    types:
      - opened
      - synchronize
    branches:
      - develop
    paths:
      - ".github/workflows/**/*.yml"
      - ".github/workflows/**/*.yaml"

jobs:
  actionlint:
    name: "✒ lint actions"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.KIRARI_TOKEN }}
          reporter: github-pr-review
          level: error